apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apiserver-tls
  namespace: garden
spec:
  secretName: apiserver-tls #생성될 secret Name
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
  - www.fredric.playground.cld
  - harbor.fredric.playground.cld
  - vault.fredric.playground.cld
  - keycloak.fredric.playground.cld
  - redis.fredric.playground.cld
  - rabbitmq.fredric.playground.cld
  - mariadb.fredric.playground.cld
  - palworld.fredric.playground.cld
  - minecraft.fredric.playground.cld
  - prometheus.fredric.playground.cld
  - grafana.fredric.playground.cld
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admission-tls
  namespace: garden
spec:
  secretName: admission-tls #생성될 secret Name
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
  - www.fredric.playground.cld
  - harbor.fredric.playground.cld
  - vault.fredric.playground.cld
  - keycloak.fredric.playground.cld
  - redis.fredric.playground.cld
  - rabbitmq.fredric.playground.cld
  - mariadb.fredric.playground.cld
  - palworld.fredric.playground.cld
  - minecraft.fredric.playground.cld
  - prometheus.fredric.playground.cld
  - grafana.fredric.playground.cld
---
