service:
  type: ClusterIP

configMaps:
  postfix-accounts.cf:
    create: true
    path: postfix-accounts.cf
    data: |
      fredric@mail.fredric.playground.cld|{SHA512-CRYPT}$6$IPZMfsKG.EN7trxE$p3E320e57xVdRwdQeYWXA0RSBpJubqfupUAQeGkeqjNQ5hsFVhUW.Wiaz7DnfiyImtJIJ8eQz2YVcvMvLgWK91
      # user@example.com|{SHA512-CRYPT}$6$PLsyDsD5kMTmQbe/$b1jT8MvuoBfs/JeBQ9fBQ0JlnWJZ377SW/OxSlNe7ldjgRQ7K4ysGfM6OpkkxQkAu7c7pR7EAR5Y4aIty2/Qi.

image:
  # Makes kube-score happy, otherwise it complains about the default pullPlicy of "IfNotPresent"
  pullPolicy: Always
