apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: main-proxy
  name: main-proxy
spec:
  containers:
  - image: nginx
    name: main-proxy
    ports:
    - containerPort: 443
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: main-proxy
  name: main-proxy
spec:
  ports:
  - nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    run: main-proxy
  type: NodePort
status:
  loadBalancer: {}
