apiVersion: v1
data:
  config.json: |-
    {
      "nodePathMap":[
      {
        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
        "paths":["/var/lib/rancher/k3s/storage","/mnt/ssd1"]
      }
      ]
    }
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: rancher/mirrored-library-busybox:1.36.1
        imagePullPolicy: IfNotPresent
  setup: |-
    #!/bin/sh
    while getopts "m:s:p:" opt
    do
        case $opt in
            p)
            absolutePath=$OPTARG
            ;;
            s)
            sizeInBytes=$OPTARG
            ;;
            m)
            volMode=$OPTARG
            ;;
        esac
    done
    mkdir -m 0777 -p ${absolutePath}
    chmod 700 ${absolutePath}/..
  teardown: |-
    #!/bin/sh
    while getopts "m:s:p:" opt
    do
        case $opt in
            p)
            absolutePath=$OPTARG
            ;;
            s)
            sizeInBytes=$OPTARG
            ;;
            m)
            volMode=$OPTARG
            ;;
        esac
    done
    rm -rf ${absolutePath}
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.json":"{\n  \"nodePathMap\":[\n  {\n    \"node\":\"DEFAULT_PATH_FOR_NON_LISTED_NODES\",\n    \"paths\":[\"/var/lib/rancher/k3s/storage\",\"/mnt/ssd1\"]\n  }\n  ]\n}","helperPod.yaml":"apiVersion: v1\nkind: Pod\nmetadata:\n  name: helper-pod\nspec:\n  containers:\n  - name: helper-pod\n    image: rancher/mirrored-library-busybox:1.36.1\n    imagePullPolicy: IfNotPresent","setup":"#!/bin/sh\nwhile getopts \"m:s:p:\" opt\ndo\n    case $opt in\n        p)\n        absolutePath=$OPTARG\n        ;;\n        s)\n        sizeInBytes=$OPTARG\n        ;;\n        m)\n        volMode=$OPTARG\n        ;;\n    esac\ndone\nmkdir -m 0777 -p ${absolutePath}\nchmod 700 ${absolutePath}/..","teardown":"#!/bin/sh\nwhile getopts \"m:s:p:\" opt\ndo\n    case $opt in\n        p)\n        absolutePath=$OPTARG\n        ;;\n        s)\n        sizeInBytes=$OPTARG\n        ;;\n        m)\n        volMode=$OPTARG\n        ;;\n    esac\ndone\nrm -rf ${absolutePath}"},"kind":"ConfigMap","metadata":{"annotations":{"objectset.rio.cattle.io/applied":"H4sIAAAAAAAA/6ySX2vbMBTFv4p2t0fHieckBMEewtqysf4JW7aXCcy1dB2rsXWFpSaU0O8+FFPoYP8e9uj74xyfc9AJ0NtvNATLDiQcCsjAYESQJ9DsGrvL78MZnZQTQoFjQxuM7Q16BfJ7Op7JM1MgFVxcXq2/Xm+rzXr7obq6+1zd3t1W1x+/bC8vKsigpc7TsGGTP2LfgXyRQYpDodzeOiPFho1yPUVMgWT6icOepBjlE59w8KTPSDNkECg+eJDw+tW0tm4aWuWOre1I7Ciyj0Eo6GWQXioQ7KNyhsfsGgOJN+yjsG68CCEgg0g4GD66/+f5lEFqBxLen+e9QQ8ZPLdMs6NzHDFadiF9cn1POgaK+WA51xhjR7nlqU0ekP2W89HRMNkd9iBhX4YX5FBk4pN15t3aGHZ/tUijg4SONXaTEHnAHf2TKHjUSbl/qGkSHkOkPtXvsKbuj9VaDC1IKFZlUy70ctE0tS5ny/lyVjbzsikWq5lZ6eUK3xqszTyZ/hTSY2wn4+uFEf0yytOPAAAA//88hrMO/QIAAA","objectset.rio.cattle.io/id":"","objectset.rio.cattle.io/owner-gvk":"k3s.cattle.io/v1, Kind=Addon","objectset.rio.cattle.io/owner-name":"local-storage","objectset.rio.cattle.io/owner-namespace":"kube-system"},"creationTimestamp":"2024-02-08T08:53:04Z","labels":{"objectset.rio.cattle.io/hash":"183f35c65ffbc3064603f43f1580d8c68a2dabd4"},"name":"local-path-config","namespace":"kube-system","resourceVersion":"4591668","uid":"93b0d3e5-fd1c-4525-9bd9-8b6cee69a8c0"}}
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/6ySX2vbMBTFv4p2t0fHieckBMEewtqysf4JW7aXCcy1dB2rsXWFpSaU0O8+FFPoYP8e9uj74xyfc9AJ0NtvNATLDiQcCsjAYESQJ9DsGrvL78MZnZQTQoFjQxuM7Q16BfJ7Op7JM1MgFVxcXq2/Xm+rzXr7obq6+1zd3t1W1x+/bC8vKsigpc7TsGGTP2LfgXyRQYpDodzeOiPFho1yPUVMgWT6icOepBjlE59w8KTPSDNkECg+eJDw+tW0tm4aWuWOre1I7Ciyj0Eo6GWQXioQ7KNyhsfsGgOJN+yjsG68CCEgg0g4GD66/+f5lEFqBxLen+e9QQ8ZPLdMs6NzHDFadiF9cn1POgaK+WA51xhjR7nlqU0ekP2W89HRMNkd9iBhX4YX5FBk4pN15t3aGHZ/tUijg4SONXaTEHnAHf2TKHjUSbl/qGkSHkOkPtXvsKbuj9VaDC1IKFZlUy70ctE0tS5ny/lyVjbzsikWq5lZ6eUK3xqszTyZ/hTSY2wn4+uFEf0yytOPAAAA//88hrMO/QIAAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: local-storage
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2024-02-08T08:53:04Z"
  labels:
    objectset.rio.cattle.io/hash: 183f35c65ffbc3064603f43f1580d8c68a2dabd4
  name: local-path-config
  namespace: kube-system
  resourceVersion: "4592985"
  uid: 93b0d3e5-fd1c-4525-9bd9-8b6cee69a8c0
