{{- range $name, $config := .Values.configMaps }}
{{- if $config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ template "dockermailserver.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    heritage: "{{ $.Release.Service }}"
    release: "{{ $.Release.Name }}"
  name: {{ regexReplaceAll "[.]" $name "-" }}
data:
  {{ $config.key | default $name }}: |
{{ tpl $config.data $ | indent 6 }}
---
{{- end }}
{{- end }}