{{- range $secret := .Values.secrets }}
{{- if $secret.create }}
apiVersion: "v1"
kind: "Secret"
metadata:
  labels:
    app.kubernetes.io/name: {{ template "dockermailserver.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    heritage: "{{ $.Release.Service }}"
    release: "{{ $.Release.Name }}"
  name: {{ regexReplaceAll "[.]" $secret.name "-" }}
data:
  {{ $secret.key | default $secret.name }}: |
{{ tpl $secret.data $ | indent 6 }}
---
{{- end }}
{{- end }}

