# Service account for the Rook-Ceph operator
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-system
  namespace: {{ .Release.Namespace }} # namespace:operator
  annotations:
    kubernetes.io/service-account.name: rook-ceph-system
type: kubernetes.io/service-account-token
---
# Service account for the CephFS CSI driver
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-cephfs-plugin-sa
  namespace: {{ .Release.Namespace }} # namespace:operator
  annotations:
    kubernetes.io/service-account.name: rook-csi-cephfs-plugin-sa
type: kubernetes.io/service-account-token
---
{{- if .Values.csi.nfs.enabled }}
# Service account for the NFS CSI driver
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-nfs-plugin-sa
  namespace: {{ .Release.Namespace }} # namespace:operator
  annotations:
    kubernetes.io/service-account.name: rook-csi-nfs-plugin-sa
type: kubernetes.io/service-account-token
---
# Service account for the NFS CSI provisioner
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-nfs-provisioner-sa
  namespace: {{ .Release.Namespace }} # namespace:operator
  annotations:
    kubernetes.io/service-account.name: rook-csi-nfs-provisioner-sa
type: kubernetes.io/service-account-token
---
{{ end }}
# Service account for the CephFS CSI provisioner
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-cephfs-provisioner-sa
  namespace: {{ .Release.Namespace }} # namespace:operator
  annotations:
    kubernetes.io/service-account.name: rook-csi-cephfs-provisioner-sa
type: kubernetes.io/service-account-token
---
# Service account for the RBD CSI driver
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-rbd-plugin-sa
  namespace: {{ .Release.Namespace }} # namespace:operator
  annotations:
    kubernetes.io/service-account.name: rook-csi-rbd-plugin-sa
type: kubernetes.io/service-account-token
---
# Service account for the RBD CSI provisioner
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-rbd-provisioner-sa
  namespace: {{ .Release.Namespace }} # namespace:operator
  annotations:
    kubernetes.io/service-account.name: rook-csi-rbd-provisioner-sa
type: kubernetes.io/service-account-token
---
# Service account for Ceph COSI driver
apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-provisioner
  namespace: {{ .Release.Namespace }} # namespace:operator
  annotations:
    kubernetes.io/service-account.name: objectstorage-provisioner
type: kubernetes.io/service-account-token
