apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-fredric.playground.cld
  namespace: istio-ingress
spec:
  dnsNames:
  - '*.fredric.playground.cld'
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  secretName: tls-fredric.playground.cld
