apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-key-pair
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-haproxy
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ames11118@gmail.com
    privateKeySecretRef:
      name: letsencrypt-haproxy
    solvers:
      - http01:
          ingress:
            class: haproxy
