apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-cicd
  namespace: cicd
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.managing.svc.cluster.local:8080/api
  resyncInterval: 10 #sec
  authentication:
    # Make sure to only have 1 authentication method defined, serviceToken/universalAuth.
    # If you have multiple authentication methods defined, it may cause issues.
    universalAuth:
      secretsScope:
        projectSlug: k8s-operator-n-t5f
        envSlug: staging # "dev", "staging", "prod", etc..
        secretsPath: "/cicd" # Root is "/"
        recursive: true # Fetch all secrets from the specified path and all sub-directories. Default is false.
      
      credentialsRef:
        secretName: infisical-universal-auth-credentials
        secretNamespace: kube-system

  managedSecretReference:
    secretName: infisical-managed-secret
    secretNamespace: cicd
    creationPolicy: "Orphan" ## Owner | Orphan (default)
    # secretType: kubernetes.io/dockerconfigjson
