###################
### istio stack ###
###################
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-egress
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubesphere-system
spec:
  finalizers:
  - kubernetes
---
######################
### istio managing ###
######################
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: default
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: forward
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: alpha
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: certs
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: cicd
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: managing
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: datastore
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: filestore
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: logging
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: game-hosting
spec:
  finalizers:
  - kubernetes
---
################################
### istio-injection disabled ###
################################
apiVersion: v1
kind: Namespace
metadata:
  labels:
    #    istio-injection: disabled
    istio-injection: disabled
  name: monitoring
spec:
  finalizers:
  - kubernetes
