# 'fullnameOverride' is deprecated. Use 'deployment.instance_name' instead.
# This is only supported for backward compatibility and will be removed in a future version.
# If 'fullnameOverride' is not "kiali" and 'deployment.instance_name' is "kiali",
# then 'deployment.instance_name' will take the value of 'fullnameOverride' value.
# Otherwise, 'fullnameOverride' is ignored and 'deployment.instance_name' is used.
fullnameOverride: "kiali"

# This is required for "openshift" auth strategy.
# You have to know ahead of time what your Route URL will be because
# right now the helm chart can't figure this out at runtime (it would
# need to wait for the Kiali Route to be deployed and for OpenShift
# to start it up). If someone knows how to update this helm chart to
# do this, a PR would be welcome.
kiali_route_url: ""

#
# Settings that mimic the Kiali CR which are placed in the ConfigMap.
# Note that only those values used by the Helm Chart will be here.
#

additional_display_details:
- annotation: kiali.io/api-spec
  icon_annotation: kiali.io/api-type
  title: API Documentation

istio_namespace: istio-system # default is where Kiali is installed

auth:
  openid: {}
  openshift: {}
  strategy: ""

clustering:
  autodetect_secrets:
    enabled: true
    label: "kiali.io/multiCluster=true"
  clusters: []

deployment:
  # This only limits what Kiali will attempt to see, but Kiali Service Account has permissions to see everything.
  # For more control over what the Kial Service Account can see, use the Kiali Operator
  accessible_namespaces:
  - "**"
  additional_service_yaml: {}
  affinity:
    node: {}
    pod: {}
    pod_anti: {}
  configmap_annotations: {}
  custom_secrets: []
  host_aliases: 
    - ip: "118.37.0.85"
      hostnames:
      - "jaeger.fredric.playground.cld"
  hpa:
    api_version: "autoscaling/v2"
    spec: {}
  image_digest: "" # use "sha256" if image_version is a sha256 hash (do NOT prefix this value with a "@")
  image_name: quay.io/kiali/kiali
  image_pull_policy: "Always"
  image_pull_secrets: []
  image_version: v1.82.0 # version like "v1.39" (see: https://quay.io/repository/kiali/kiali?tab=tags) or a digest hash
  ingress:
    additional_labels: {}
    class_name: nginx
    enabled: false
    override_yaml:
      metadata:
        annotations:
          cert-manager.io/cluster-issuer: "ca-issuer"
      spec:
        ingressClassName: nginx
        rules:
        - host: "kiali.fredric.playground.cld"
          http:
            paths:
            - path: /
              pathType: "Prefix"
              backend: 
                service:
                  name: kiali
                  port: 
                    number: 20001
        tls:
        - hosts:
          - kiali.fredric.playground.cld
          secretName: kiali.fredric.playground.cld-tls
  instance_name: "kiali"
  logger:
    log_format: "text"
    log_level: "info"
    time_field_format: "2006-01-02T15:04:05Z07:00"
    sampler_rate: "1"
  node_selector: {}
  pod_annotations: {}
  pod_labels: {}
  priority_class_name: ""
  replicas: 1
  resources:
    requests:
      cpu: "10m"
      memory: "64Mi"
    limits:
      memory: "1Gi"
  secret_name: "kiali"
  security_context: {}
  service_annotations: {}
  service_type: ""
  tolerations: []
  version_label: v1.82.0 # v1.39 # v1.39.0 # see: https://quay.io/repository/kiali/kiali?tab=tags
  view_only_mode: false

external_services:
  prometheus:
    #url: http://prometheus.alpha.svc:9090
    #url: http://prometheus.istio-system.svc:9090
    #url: http://kube-prometheus-prometheus.monitoring.svc:9090
    url: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
  grafana:
    enabled: true
    auth:
      password: secret:auth-secrets:global
      insecure_skip_verify: true
    in_cluster_url: http://kube-prometheus-stack-grafana.monitoring.svc:80
    url: https://grafana.fredric.playground.cld
    dashboards: []
      #      - name: "Istio Service Dashboard"
      #      - name: "Istio Workload Dashboard"
      #      - name: "Istio Mesh Dashboard"
      #      - name: "Istio Control Plane Dashboard"
      #      - name: "Istio Performance Dashboard"
      #      - name: "Istio Wasm Extension Dashboard"
  tracing:
    enabled: true
    auth:
      insecure_skip_verify: true
    provider: jaeger
    in_cluster_url: http://jaeger-operator-jaeger-query.istio-system.svc:16685
    use_grpc: true
    url: https://jaeger.fredric.playground.cld
  custom_dashboards:
    enabled: false
  istio:
    root_namespace: istio-system
    component_status:
      enabled: true
      components:
        - app_label: istiod
          is_core: true
        - app_label: gateway
          is_core: true
          is_proxy: true
          namespace: istio-ingress
        - app_label: gateway
          is_core: true
          is_proxy: true
          namespace: istio-egress

identity: {}
  #cert_file:
  #private_key_file:

kiali_feature_flags:
  certificates_information_indicators:
    enabled: true
    secrets:
    - cacerts
    - istio-ca-secret
  disabled_features: []
  validations:
    ignore: ["KIA1301"]

login_token:
  signing_key: "kiali_authsecret"

server:
  port: 20001
  #node_port:
  observability:
    metrics:
      enabled: true
      port: 9090
  web_root: ""
