annotations:
  category: Infrastructure
  images: |
    - name: argo-workflow-cli
      image: docker.io/bitnami/argo-workflow-cli:3.5.5-debian-12-r5
    - name: argo-workflow-controller
      image: docker.io/bitnami/argo-workflow-controller:3.5.5-debian-12-r3
    - name: argo-workflow-exec
      image: docker.io/bitnami/argo-workflow-exec:3.5.5-debian-12-r4
  licenses: Apache-2.0
apiVersion: v2
appVersion: 3.5.5
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.x.x
- condition: mysql.enabled
  name: mysql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 10.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Argo Workflows is meant to orchestrate Kubernetes jobs in parallel. It
  uses DAG and step-based workflows
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/argo-workflows/img/argo-workflows-stack-220x234.png
keywords:
- Devops
- Kubernetes
- Jobs
- Continuous delivery
- Continous deployment
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: argo-workflows
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/argo-workflows
version: 8.0.5
